---
# Copyright (C) 2013-2016 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2014-2016 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

  # This task is needed for Ansible to correctly pass the 'secret' variable to
  # other roles
- name: Define variables used by Ansible roles
  ansible.builtin.set_fact:
    secret: '{{ secret }}'

- name: Create secret directories on Ansible Controller
  ansible.builtin.file:
    path: '{{ secret + "/" + item }}'
    state: 'directory'
    mode: '0755'
  become: False
  delegate_to: 'localhost'
  loop: '{{ [secret__directories, secret_directories | d([])] | flatten }}'
  when: (secret__directories or secret_directories | d()) and item
  changed_when: False

## DKN Workaround to avoid empty secret directory
- name: Check if secret directory is not empty
  find:
    path: '{{ secret }}'
  register: files_found
  delegate_to: 'localhost'

- name: Fail if secret directory is empty
  fail:
    msg: "Secret directory is empty!!"
  when: files_found.examined == 0
