---
# Copyright (C) 2016      Mariano Barcia <mariano.barcia@gmail.com>
# Copyright (C) 2016-2019 Maciej Delmanowski <drybjed@gmail.com>
# Copyright (C) 2016-2019 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-only

- name: "Restart php-fpm"
  service:
    name: "php{{ php__version }}-fpm"
    state: 'restarted'
  when: '"fpm" in php__server_api_packages'

- name: "Reload php-fpm"
  service:
    name: "php{{ php__version }}-fpm"
    state: 'reloaded'
  when: '"fpm" in php__server_api_packages'

# For Multiversion

- name: "Restart php-fpm multiversion"
  ansible.builtin.service:
    name: "php{{ item }}-fpm"
    state: 'restarted'
  when: '"fpm" in php__server_api_packages'
  loop: '{{ php__register_all_installed_versions.stdout_lines }}'
